[package]
name = "curry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.2.0"
blake2 = "0.10.6"
bls-signatures = "0.15.0"
rand = "0.8.5"
